import type { Metadata } from "next";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import { GetShopCategoriesTreeList } from "@/services/shopActions";
// import Providers from "./providers";
import localFont from "next/font/local";

const iranyekan = localFont({
  variable: "--font-iranyekan",
  src: [
    {
      path: "fonts/iranyekanweblight.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "fonts/iranyekanwebregular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/iranyekanwebbold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "fonts/iranyekanwebbold.woff2",
      weight: "900",
      style: "normal",
    },
  ],
});

const pelak = localFont({
  variable: "--font-pelak",
  src: [
    {
      path: "fonts/Pelak-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/Pelak-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

const noora = localFont({
  variable: "--font-noora",
  src: [
    {
      path: "fonts/Noora Fa-En 03 Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
});

const dana = localFont({
  variable: "--font-dana",
  src: [
    {
      path: "fonts/dana-fanum-regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
});
export const metadata: Metadata = {
  title: "تکنو صاف",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const result = await GetShopCategoriesTreeList();

  return (
    <html lang="fa-IR" dir="rtl" className="scroll-smooth w-screen">
      <body
        className={`${iranyekan.variable} ${pelak.variable} ${noora.variable} ${dana.variable} ${iranyekan.className} antialiased overflow-x-hidden overflow-y-auto w-full h-full bg-[#f9f9f9]`}
      >
        <Navbar categories={result?.data} />
        <main className="container customSm:max-w-[566px]  w-full mx-auto mb-20 px-2 lg:px-0 h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
